### ISSUE TITLE
Update repository URL on Packagist

### ISSUE THREAD

**Issue by mbrodala** [phlylabs/idna-convert#1]
On [Packagist](https://packagist.org/packages/phpwhois/idna-convert) the repository for this package is still https://github.com/phpWhois/idna-convert which breaks every dependent package since neither dist nor source can be downloaded.

Please update the VCS repository URL on Packagist.

**Comment by phlylabs** [comment]
Hi Mathias,

as just stated in our private email conversation, I cannot fix anything within the phpWhois project. Please contact the guys over there directly: https://github.com/phpWhois/phpWhois

Thx!

**Comment by mbrodala** [comment]
@phlylabs I'll get in touch with them.

**Comment by mbrodala** [comment]
@phlylabs OK, now for real. What's your package name on Packagist? I am able to find [php-idna-converter/php-idna-converter](https://packagist.org/packages/php-idna-converter/php-idna-converter) which supposedly is _phlyLabs' pure PHP IDNA Converter_ but that package points to [this Github repository](https://github.com/php-mod/php-idna-converter) instead.

Can you clear this up?

**Comment by phlylabs** [comment]
I'm sorry for the mess. Unfortunately I was a little late to the party, so I rather recently put the class on GitHub and Packagist.
Although I tried to contact a few of the authors of cloned packages, most of them did not respond, which leads to unnecessary duplicates.
This is the "official" URL of my Packagist package: https://packagist.org/packages/mso/idna-convert

**Comment by mbrodala** [comment]
Yeah, found that out in the meantime. Would you mind putting out a stable release? Right now we at TYPO3 would need to require `0.9.x-dev`.

**Comment by phlylabs** [comment]
Sure, will do. Expect it until the end of the week.

**Comment by mbrodala** [comment]
Thanks.

**Comment by phlylabs** [comment]
Hi,

```
require {
      "mso/idna-convert": "0.9.*"
}
```
should work fine now

**Comment by mbrodala** [comment]
Thanks, I'll give it a try. :-)
